### ISSUE TITLE
how to store the notebooks locally on my hard disk?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [a-ghorbani/docker-spark-jupyter-scala#1]
I would like to store the notebooks locally on my hard disk.

In simpler types of containers I've used volumes and mapped them on my physical disk.

Would you be so kind to recommend an approach, or better add the appropriate command to the README file?

Thanks in advance

(take into account that the links to Spark on the existing README are broken)

**Comment by a-ghorbani** [comment]
Thanks for pointing out the issues.
